### ISSUE TITLE
add conductivity and brightness

### ISSUE THREAD

**Issue by Beejeedeb** [tim-hellhake/mi-flora-adapter#11]
Hi Tim,
Is it also possible to add conductivity (fertility of the soil) and brightness?

I found some more information about the mi Flora maybe something you can use in your code.

https://github.com/vrachieru/xiaomi-flower-care-api

**Comment by tim-hellhake** [comment]
I will definitely add this but it may take a few days.
I'll get back to you.

**Comment by tim-hellhake** [comment]
I finally found time to do this.
The values look plausible, but the `brightness` property looks a bit strange.
I'm not sure why this is happening.
I have to analyze this further.

**Comment by Beejeedeb** [comment]
I will check the update if it is available and see if I can find somemore information

**Comment by Beejeedeb** [comment]
isnt there a difference between brightness of a light bulb which can be changed with a slider and illuminance for light sensor? Different attributes and (level)properties. For this I think a normal luminance lux value should suffice.

**Comment by tim-hellhake** [comment]
Makes sense.
There seems to be a fallback in the gateway which assumes that a property called `brightness` is always the brightness of a light bulb in percent.
Renaming the property to `illuminance` should fix the issue.

**Comment by tim-hellhake** [comment]
The values of the light sensor should be displayed correctly now.
If you have any problems please open an issue.
