### ISSUE TITLE
Add more description to the setting?

### ISSUE THREAD

**Issue by flatsiedatsie** [tim-hellhake/mi-flora-adapter#2]
The 'seconds between polling' option: it's unclear to me which choice I should make.

What happens if I leave it at 0? What would be a good default?

I would suggest adding this to the description of the field.

**Comment by tim-hellhake** [comment]
The adapter connects to the device, reads the value, disconnects, and waits for the specified number of seconds before reconnecting again.
The value should be as high as possible to save battery capacity.
I'll add this to the documentation.

**Comment by flatsiedatsie** [comment]
Thanks! I had a calculation. To check once a day it would be once every 86400 seconds.

Perhaps change it to poll in minutes or hours instead?

Also, I noticed in the code that the default is 30. It might be nice to mention that if you leave it at 0, it will be 30. Or just change it to show 30 by default?

**Comment by tim-hellhake** [comment]
> Perhaps change it to poll in minutes or hours instead?

I think minutes should be a good compromise.

> Or just change it to show 30 by default?

I'll make it show the default value in the settings.
