### ISSUE TITLE
Flower care or Flower mate?

### ISSUE THREAD

**Issue by flatsiedatsie** [tim-hellhake/mi-flora-adapter#3]
My devices advertise themselves as `Flower mate` and not Flower care. 

I suspect I have an older version.

Perhaps the adapter could support either? The reason is that I don't want to update their firmware, for privacy reasons. I don't want to install the Xiaomi app, not even for a minute.

**Comment by tim-hellhake** [comment]
No problem, I'll add `Flower mate` too

**Comment by flatsiedatsie** [comment]
It's working now, thanks!
