### ISSUE TITLE
Idea: add persistence

### ISSUE THREAD

**Issue by flatsiedatsie** [tim-hellhake/mi-flora-adapter#5]
Currently, if you reboot the Gateway, the Mi Flora devices will indicate 0% until the first scan. If you only request the values once a day, like me, this means you have an entire day where you can't quickly check the current value.

Perhaps the last values could be stored in a json file and re-presented to the gateway upon init?

**Comment by tim-hellhake** [comment]
Good point, I wonder if it would make sense to add such functionality to the gateway.
